Enpoints, api, database_invoice and updated UserForm
noQ-sweden/noq_backend_python pull request #35
Opened 2024-07-09 05:30 UTC by xelleze

Endpoints in view.py:

Handläggaren måste kunna registrera den hemlöse //manual_user_registration

Måste kunna se hur många platser lediga boende //empty_resident_view

Kunna motta faktura från härbärgen //invoice_create

Hur många nätter en brukare har sovit på specifkt härberge eller totalt //user_shelter_stay_count_view

API:

Invoice has been integrated  /api/old/create_invoice and /api/old/get_invoice/{invoice_id}

Database:

Added Invoice

Form update:

Updated UserForm to include more fields, email validation, gender widget and region field

2024-07-09 17:26 UTC, jani-at-noq requested changes
Bra jobbat med ändringar. Jag har några kommentarer, men allt behöver inta fixas. Det mest akut är att man skapar inte Client när man skapar ny användare. Model ändringar för invoice är också viktiga.

2024-07-09 17:26 UTC, jani-at-noq commented on noq_django/backend/forms.py
>  class UserForm(forms.ModelForm):
Nånting är fel. Vet inte vad eller var. Om jag skapar användare (user), skapas ingen client. Om jag tittar på Användarelistan visas nya användare, men Client listan har inte användaren. Man kan logga in som användare, men man kan inte boka plats via api/user/request_booking.

2024-07-09 17:33 UTC, jani-at-noq commented
Faktura innehåll (https://www.skatteverket.se/foretag/moms/saljavarorochtjanster/momslagensregleromfakturering.4.58d555751259e4d66168000403.html)
Följande uppgifter ska finnas med på en fullständig faktura:
- Datum för utfärdandet av fakturan.
- Ett unikt löpnummer för varje faktura baserat på en eller flera serier.
- Säljarens momsregistreringsnummer.
- Köparens momsregistreringsnummer om köparen är betalningsskyldig för köpet, så kallad omvänd betalningsskyldighet.
- Säljarens och köparens namn och adress.
- Varornas mängd och art eller tjänsternas omfattning och art.
- Datum då försäljningen av varorna eller tjänsterna utförts eller slutförts eller det datum då förskotts- eller a conto-betalning skett, om ett sådant datum kan fastställas och det skiljer sig från fakturadatumet.
- Beskattningsunderlaget för varje skattesats eller undantag, enhetspriset exklusive moms, samt eventuell prissänkning eller rabatt som inte ingår i enhetspriset.
- Tillämpad skattesats.
- Det momsbelopp som ska betalas. Om säljaren använder vinstmarginalbeskattning på transaktionen ska momsbelopp inte anges i fakturan.

2024-07-09 17:38 UTC, jani-at-noq commented
Du har ändring i model. Då ska du också inkludera migration fil i patch (efter du har gjort makemigration). Vi har inte haft dom i github tidigare, men det är fel. Vi ska ha migration filer på plats så att vi kan uppdatera db rätt från en version till den andra.

2024-07-17 12:34 UTC, jani-at-noq commented on noq_django/backend/forms.py
>  class UserForm(forms.ModelForm):
Ok. Kanske det är som det ska i så fall. Men handläggare måste skapa både user och client innan brukare kan boka sovplats. Ska testa mer på fredag. Men ok från review perpektiv baserad på din kommentar.

2024-07-17 12:38 UTC, jani-at-noq approved these changes
Ser bra ut.

2024-07-18 06:32 UTC, Mrsluggan approved these changes

2024-07-18 15:15 UTC, merged