fixed bug
noQ-sweden/noq_backend_python pull request #48
Opened 2024-09-06 10:17 UTC by natischmidt

fixed bug, now u can add new host while leaving the blocked users empty if u dont need to add it.

2024-09-06 20:25 UTC, jani-at-noq requested changes

2024-09-06 20:25 UTC, jani-at-noq commented on noq_django/backend/migrations/0002_roomtype_alter_available_table_alter_booking_table_and_more.py
This should not be part of PR

2024-09-06 20:25 UTC, jani-at-noq commented on noq_django/backend/migrations/0003_remove_booking_room_alter_available_table_and_more.py
This should not be part of PR

2024-09-06 20:25 UTC, jani-at-noq commented on noq_django/backend/migrations/0004_alter_product_type.py
This should not be part of PR

2024-09-06 20:25 UTC, jani-at-noq commented on noq_django/backend/migrations/0005_merge_20240714_1246.py
This should not be part of PR

2024-09-06 20:25 UTC, jani-at-noq commented on noq_django/backend/migrations/0007_merge_20240830_1009.py
This should not be part of PR

2024-09-06 20:25 UTC, jani-at-noq commented on noq_django/backend/migrations/0008_alter_host_blocked_clients.py
This should be 0007

2024-09-06 20:25 UTC, jani-at-noq commented on noq_django/backend/migrations/0008_alter_host_blocked_clients.py
> +        ('backend', '0007_merge_20240830_1009'),
Dependency should be 0006_invoice_buyer_address_invoice_buyer_name_and_more

2024-09-06 20:25 UTC, jani-at-noq commented on noq_django/backend/models.py
Looks good!

2024-09-06 20:25 UTC, jani-at-noq commented on .idea/.gitignore
I'm a bit against adding Pycharm related files to the repo. Why you want to add them (.idea folder)?

2024-09-06 21:20 UTC, natischmidt commented
@jani-at-noq just started using vscode, bc my liscense for Intellij ran out.. still getting used to it - wasnt intenionall i'll fix it

2024-09-08 07:53 UTC, jani-at-noq approved these changes
Nu är det bara två filer som det ska vara. Ok för min del.

2024-09-08 08:27 UTC, merged