Connecting host client django
noQ-sweden/noq_backend_python pull request #52
Opened 2024-09-13 09:31 UTC by MarioDanilo0111

- Added a created_by field to the Host model to track the user who created each host.
- Updated the caseworkers field in the Host model to ensure proper relationships between users and hosts.
- Implemented changes to the Django admin interface to manage and filter caseworkers more efficiently.
- Refined the add_caseworkers function to ensure caseworkers are correctly assigned to multiple hosts based on the 
   created_by field.
- Generated new migrations to reflect changes in the models.

2024-09-14 09:03 UTC, jani-at-noq requested changes
Behövs små fixar för model och admin ändringar, men generate_data script funkar inte som du har tänkt. Den genererar ingen data för hosts_caseworkers tabell.

2024-09-14 09:03 UTC, jani-at-noq commented on noq_django/backend/scripts/generate_data.py
> +        hosts_created_by_user = Host.objects.filter(created_by=new_user)
Du skapar inga hosts med created_by fält i scriptet, så denna raden returnerar ingenting. Jag tror det bästa sättet är nära det du har kommenterat bort.

1. hämta host som är knyten till user.host@test.nu
2. ta region from hosten
3. Sätt fält host.caseworkers för alla host i regionen till user.caseworker@test.nu

Då borde du ha alla host i region x knyten till test användare för caseworker. Ta borta koden som körs just nu och gör ändringar ovan till koden du har kommenterad bort (rader 140-159)

2024-09-14 09:05 UTC, jani-at-noq commented
Kolla också varför tester fallerar. Alla python test cases ska vara pass efter ändringar.

2024-09-15 16:54 UTC, jani-at-noq commented on noq_django/backend/admin.py
> +
Ser bra ut i det senaste commit. Jag stänger.

2024-09-15 16:59 UTC, jani-at-noq approved these changes
Filter i sidomeny och filtrering av users i host-user relation funkar inte som det ska, men vi ska skriva egen story för dom. I listan för host-user, bara caseworkers ska listas. I sidomeny ska också caseworkers listas och när man trycker på namn ska host listan visa bara hosts som är kopplat till den specifika caseworker. Nu är det bara Alla som alternativ.

Men vi leverar detta så vi kan börja använda uppdaterad host model.

![image](https://github.com/user-attachments/assets/5fd15d07-ab13-4fd2-9f61-7152aafeef11)

![image](https://github.com/user-attachments/assets/8a05a6a4-a4a5-4532-8377-39198a5c078a)

2024-09-15 17:01 UTC, jani-at-noq requested changes
Märkte precis att testerna fallerar. Dom måste man fixa innan man kan merga.

2024-09-16 18:19 UTC, jani-at-noq approved these changes
Ser bra ut, ok för min del.

2024-09-17 10:27 UTC, xelleze submitted a review, later dismissed

2024-09-17 20:39 UTC, xelleze commented
@MarioDanilo0111 check the conflict in the admin.py file

2024-09-18 20:54 UTC, MarioDanilo0111 commented
@xelleze fixed the issues, you can run a review.

2024-09-18 21:13 UTC, xelleze approved these changes

2024-09-19 04:10 UTC, merged