Lista over bostallen backend
noQ-sweden/noq_backend_python pull request #57
Opened 2024-09-26 17:27 UTC by marco-noq

Issues: #554 och #564:
 Innehåller små tillägg för både listan med boställen och bokningsförfrågan.
B.la.

- Tillägg av fler produkttyper.
- bookable :boolean
- och en kontroll i api:t så man inte bokar någon produkt som inte är bokningsbar.

2024-09-27 17:23 UTC, jani-at-noq requested changes
Looks good. You should change the return code for non bookable error.

2024-09-27 17:23 UTC, jani-at-noq commented on noq_django/rest_api/api/user_api.py
> +
remove spaces

2024-09-27 17:23 UTC, jani-at-noq commented on noq_django/rest_api/api/user_api.py
> +            raise HttpError(404, "This product is not bookable.")
use 422 Unprocessable Entity instead

2024-09-30 15:43 UTC, natischmidt requested changes
will approve after changes been done

2024-10-01 09:13 UTC, natischmidt approved these changes

2024-10-01 09:14 UTC, natischmidt commented
Vad saknas nu?

2024-10-01 12:54 UTC, natischmidt commented
vad jag ser är alla ändringar gjort nu

2024-10-03 17:11 UTC, jani-at-noq approved these changes

2024-10-03 17:11 UTC, merged