Noq 599
noQ-sweden/noq_backend_python pull request #71
Opened 2024-10-21 12:49 UTC by tobbe-joh

2024-10-21 21:11 UTC, jani-at-noq requested changes
Ser bra ut, jag är lite osäker hur update eller create funkar om du har tom string som input. Lägg till test fall för det.

2024-10-22 08:26 UTC, tobbe-joh commented on noq_django/rest_api/api/api_schemas.py
> +class UserRegistrationSchema(Schema):
smart! namngivning är så svårt!

2024-10-22 14:57 UTC, tobbe-joh commented on noq_django/rest_api/api/test/test_caseworker_crud_user.py
> +   def test_register_user(self):
nu finns test case ifall det är empty fields, alltså en tom sträng ""

2024-10-23 17:15 UTC, jani-at-noq approved these changes
Looks good for me.

2024-10-30 12:10 UTC, merged

2024-10-30 12:10 UTC, natischmidt commented
👍