570 bug user can make conflicting bookings
noQ-sweden/noq_backend_python pull request #73
Opened 2024-10-29 12:05 UTC by AhmadHajAhmad

The added code ensures that users cannot create overlapping bookings. For example, if a user books a room from 03/11 to 05/11 (Booking 1) and then tries to book another from 04/11 to 07/11 (Booking 2), the system will reject the second booking due to the date conflict.

The logic also allows modifying existing bookings without triggering overlap validation errors.

2024-10-30 11:52 UTC, jani-at-noq requested changes
Ändringen ser bra ut och funkar. Du behöver lägga till test fall också, så vi upptäcker liknande problem i framtiden. Du ska ha ett test fall som täcker alla skenarios.

2024-10-30 11:52 UTC, jani-at-noq commented on noq_django/backend/models.py
> +        user=self.user,
Indentera för läsbarhet

2024-10-30 22:14 UTC, jani-at-noq approved these changes
Looks good now. Great work Ahmad!

2024-10-30 22:18 UTC, AhmadHajAhmad commented on noq_django/backend/models.py
> +        user=self.user,
It is fixed now.

2024-10-31 10:08 UTC, tobbe-joh approved these changes
Nice!

2024-10-31 21:37 UTC, merged